[project]
name = "simulate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "notebook>=7.4.5",
    "pyproj>=3.7.2",
]
